// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQLK3VKlUxAMxDp5aqfPrR-CoSHYuoNE',
    appId: '1:648087513665:web:e8c88daf5abbff72c3b4c0',
    messagingSenderId: '648087513665',
    projectId: 'flutter-mini-project-824fb',
    authDomain: 'flutter-mini-project-824fb.firebaseapp.com',
    storageBucket: 'flutter-mini-project-824fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZBFuAJDhv3rIJKWV1wCc5np6-5ZfUAi4',
    appId: '1:648087513665:android:56182ada666f9d77c3b4c0',
    messagingSenderId: '648087513665',
    projectId: 'flutter-mini-project-824fb',
    storageBucket: 'flutter-mini-project-824fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtP1O_ekKm2UDLc7TRcaX3rEz3RRNrPw4',
    appId: '1:648087513665:ios:07eae32d9a06e13ac3b4c0',
    messagingSenderId: '648087513665',
    projectId: 'flutter-mini-project-824fb',
    storageBucket: 'flutter-mini-project-824fb.appspot.com',
    iosBundleId: 'com.example.miniProject9ach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtP1O_ekKm2UDLc7TRcaX3rEz3RRNrPw4',
    appId: '1:648087513665:ios:32501292536ca587c3b4c0',
    messagingSenderId: '648087513665',
    projectId: 'flutter-mini-project-824fb',
    storageBucket: 'flutter-mini-project-824fb.appspot.com',
    iosBundleId: 'com.example.miniProject9ach.RunnerTests',
  );
}
